// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package main

import (
	"sync"

	"github.com/ktr0731/evans/prompt"
)

// Ensure, that PromptMock does implement prompt.Prompt.
// If this is not the case, regenerate this file with moq.
var _ prompt.Prompt = &PromptMock{}

// PromptMock is a mock implementation of prompt.Prompt.
//
//	func TestSomethingThatUsesPrompt(t *testing.T) {
//
//		// make and configure a mocked prompt.Prompt
//		mockedPrompt := &PromptMock{
//			GetCommandHistoryFunc: func() []string {
//				panic("mock out the GetCommandHistory method")
//			},
//			InputFunc: func() (string, error) {
//				panic("mock out the Input method")
//			},
//			SelectFunc: func(message string, options []string) (int, string, error) {
//				panic("mock out the Select method")
//			},
//			SetCompleterFunc: func(c prompt.Completer)  {
//				panic("mock out the SetCompleter method")
//			},
//			SetPrefixFunc: func(prefix string)  {
//				panic("mock out the SetPrefix method")
//			},
//			SetPrefixColorFunc: func(color prompt.Color)  {
//				panic("mock out the SetPrefixColor method")
//			},
//		}
//
//		// use mockedPrompt in code that requires prompt.Prompt
//		// and then make assertions.
//
//	}
type PromptMock struct {
	// GetCommandHistoryFunc mocks the GetCommandHistory method.
	GetCommandHistoryFunc func() []string

	// InputFunc mocks the Input method.
	InputFunc func() (string, error)

	// SelectFunc mocks the Select method.
	SelectFunc func(message string, options []string) (int, string, error)

	// SetCompleterFunc mocks the SetCompleter method.
	SetCompleterFunc func(c prompt.Completer)

	// SetPrefixFunc mocks the SetPrefix method.
	SetPrefixFunc func(prefix string)

	// SetPrefixColorFunc mocks the SetPrefixColor method.
	SetPrefixColorFunc func(color prompt.Color)

	// calls tracks calls to the methods.
	calls struct {
		// GetCommandHistory holds details about calls to the GetCommandHistory method.
		GetCommandHistory []struct {
		}
		// Input holds details about calls to the Input method.
		Input []struct {
		}
		// Select holds details about calls to the Select method.
		Select []struct {
			// Message is the message argument value.
			Message string
			// Options is the options argument value.
			Options []string
		}
		// SetCompleter holds details about calls to the SetCompleter method.
		SetCompleter []struct {
			// C is the c argument value.
			C prompt.Completer
		}
		// SetPrefix holds details about calls to the SetPrefix method.
		SetPrefix []struct {
			// Prefix is the prefix argument value.
			Prefix string
		}
		// SetPrefixColor holds details about calls to the SetPrefixColor method.
		SetPrefixColor []struct {
			// Color is the color argument value.
			Color prompt.Color
		}
	}
	lockGetCommandHistory sync.RWMutex
	lockInput             sync.RWMutex
	lockSelect            sync.RWMutex
	lockSetCompleter      sync.RWMutex
	lockSetPrefix         sync.RWMutex
	lockSetPrefixColor    sync.RWMutex
}

// GetCommandHistory calls GetCommandHistoryFunc.
func (mock *PromptMock) GetCommandHistory() []string { _ = "STUB: not implemented"; return nil }

// GetCommandHistoryCalls gets all the calls that were made to GetCommandHistory.
// Check the length with:
//
//	len(mockedPrompt.GetCommandHistoryCalls())
func (mock *PromptMock) GetCommandHistoryCalls() []struct {
} {
	_ = "STUB: not implemented"
	return nil
}

// Input calls InputFunc.
func (mock *PromptMock) Input() (string, error) { _ = "STUB: not implemented"; return "", nil }

// InputCalls gets all the calls that were made to Input.
// Check the length with:
//
//	len(mockedPrompt.InputCalls())
func (mock *PromptMock) InputCalls() []struct {
} {
	_ = "STUB: not implemented"
	return nil
}

// Select calls SelectFunc.
func (mock *PromptMock) Select(message string, options []string) (int, string, error) {
	_ = "STUB: not implemented"
	return 0, "", nil
}

// SelectCalls gets all the calls that were made to Select.
// Check the length with:
//
//	len(mockedPrompt.SelectCalls())
func (mock *PromptMock) SelectCalls() []struct {
	Message string
	Options []string
} {
	_ = "STUB: not implemented"
	return nil
}

// SetCompleter calls SetCompleterFunc.
func (mock *PromptMock) SetCompleter(c prompt.Completer) { _ = "STUB: not implemented"; return }

// SetCompleterCalls gets all the calls that were made to SetCompleter.
// Check the length with:
//
//	len(mockedPrompt.SetCompleterCalls())
func (mock *PromptMock) SetCompleterCalls() []struct {
	C prompt.Completer
} {
	_ = "STUB: not implemented"
	return nil
}

// SetPrefix calls SetPrefixFunc.
func (mock *PromptMock) SetPrefix(prefix string) { _ = "STUB: not implemented"; return }

// SetPrefixCalls gets all the calls that were made to SetPrefix.
// Check the length with:
//
//	len(mockedPrompt.SetPrefixCalls())
func (mock *PromptMock) SetPrefixCalls() []struct {
	Prefix string
} {
	_ = "STUB: not implemented"
	return nil
}

// SetPrefixColor calls SetPrefixColorFunc.
func (mock *PromptMock) SetPrefixColor(color prompt.Color) { _ = "STUB: not implemented"; return }

// SetPrefixColorCalls gets all the calls that were made to SetPrefixColor.
// Check the length with:
//
//	len(mockedPrompt.SetPrefixColorCalls())
func (mock *PromptMock) SetPrefixColorCalls() []struct {
	Color prompt.Color
} {
	_ = "STUB: not implemented"
	return nil
}
